mkdir "1 Scope" 	
mkdir "2 Normative references" 	
mkdir "3 Terms and definitions" 	
mkdir "4 Symbols" 	
mkdir "5 Application of ISO 12215-7" 	
mkdir "5.1 General" 	
mkdir "6 Main dimensions - data and areas" 	
mkdir "6.1 Dimensions of the platform" 	
mkdir "6.2 Areas" 	
mkdir "7 Dimensions and pressure for panels and stiffeners under local loads" 	
mkdir "7.1 General" 	
mkdir "7.2 Example of application on multihulls" 
mkdir "7.3 Other topics on panel or stiffener dimensions"
mkdir "8 Local pressure adjusting factors" 	
mkdir "8.1 General requirements" 	
mkdir "9 Local design pressures for multihulls" 
mkdir "9.1 General" 	
mkdir "9.2 Limits of application" 	
mkdir "9.3 Tables defining the local design pressures for multihulls" 	
mkdir "9.4 Design pressure for trimaran floats PTRF" 	
mkdir "9.5 Design pressure on watertight bulkheads and integral tanks" 	
mkdir "10 Further treatment of structural elements subject to local loads" 	
mkdir "11 Assessment of multihulls rudder and appendages" 	
mkdir "12 Global loads" 	
mkdir "12.1 General" 	
mkdir "12.2 Most frequent structural arrangements" 	
mkdir "12.3 Global loads to be checked" 	
mkdir "12.4 Design stresses under global loads" 	
mkdir "12.5 Global load case 1: Diagonal load in quartering sea" 	
mkdir "12.6 Global load case 2: Rig loads" 	
mkdir "12.7 Combination of diagonal load LC1 and rig load LC2 for sailing multihulls" 	
mkdir "12.8 Global load case 3: Asymmetric broaching of sailing multihulls" 	
mkdir "12.9 Global load case 4: Longitudinal broaching / pitchpoling" 	
mkdir "12.10 Global load case 5: Longitudinal force/shock on one hull" 	
mkdir "12.11 Global load case LC 6: Bending moment on beams connecting hulls for non-sailing catamarans" 	
mkdir "13 Structural arrangement for global loads" 	
mkdir "14 Multihulls used as workboats" 	
mkdir "15 Information to be included in the owner's manual" 	
mkdir "15.1 General"
mkdir "15.2 Respect of maximum loaded displacement" 	
mkdir "15.3 Operational guidance" 	
mkdir "15.4 Possibility of outer skin damage" 	
mkdir "15.5 Usage as a workboat" 	
mkdir "Annex A (normative) Application declaration of ISO 12215-7"
mkdir "Annex B (informative) Established practice Tables and calculation for global loads assessment"
mkdir "Annex C (informative) Established practice details" 
mkdir "Annex D (informative) Technical background and example of torsional moment analysis with differential deflection of crossbeams" 
mkdir "Annex ZA (informative) Relationship between this European Standard and the essential requirements of Directive 2013/53/EU aimed to be covered"
mkdir "Bibliography" 	